LEARNAcademy/classroom-admin

app/models/announcement.rb
app/models/user.rb
app/notifications/new_announcement_notification.rb
config/locales/en.yml

ID number: 79
Branch name: notifications
Description: Moved over code for notifications, modified message in navbar bell
Link to ticket: https://www.notion.so/2022-Delta-Internship-6af24e8d3bb349ea8fe44f3d6351f036?p=129d5c97311542b4a411a67d836389e2&pm=s
Notes for the reviewer: Destroying an announcement will also destroy the notification associated with it. 
Contributors: Gene and Don

🧹Moved over code/modified message for notifications

---

app/views/devise/registrations/edit.html.erb
app/views/shared/_account_navbar.html.erb
app/views/shared/_navbar.html.erb

ID number: 79
Branch name: profile
Description: 
Link to ticket: https://www.notion.so/2022-Delta-Internship-6af24e8d3bb349ea8fe44f3d6351f036?p=9bd205b0e8b749679a76cfec7f7358f2&pm=s
Contributors: Don, Luis, Will, Nicole, Logan, Gene

💄Rails: Profile tab

---

app/controllers/admin/application_controller.rb
app/dashboards/student_dashboard.rb
app/models/assessment.rb
app/models/student.rb
db/seeds.rb

ID number: [74]
Branch name: update-seed
Description: 🧹 [74] Rails:Update Seeds
Link to ticket: https://www.notion.so/2022-Delta-Internship-6af24e8d3bb349ea8fe44f3d6351f036?p=e68a3ab7fdf549c3b6ca3d1f981de16e&pm=s
Notes for the reviewer: 
Contributors: the LearnTerns

updated db seed

---

app/controllers/announcements_controller.rb
app/controllers/notifications_controller.rb
app/views/shared/_notifications.html.erb
app/views/shared/_right_nav.html.erb

ID number: [87]
Branch name: announcement-link
Description: Removed access to announcement and notifications by students. 
Link to ticket: https://www.notion.so/2022-Echo-Internship-07a11d3d30da40098b4ec56c93419db0?p=63763dbc88f749858e811b589be46b24&pm=s
Notes for the reviewer: 
Contributors: Elijah, Francisco and Gene

🐛 Announcement link

---

app/controllers/admin/announcements_controller.rb
app/dashboards/announcement_dashboard.rb
app/models/announcement.rb
app/notifications/new_announcement_notification.rb
app/views/layouts/admin/application.html.erb
db/migrate/20221109173553_add_user_reference_to_announcement.rb
db/schema.rb

ID number: 86
Branch name: notification-bug
Description: Fixed bug involving who created the announcement.
Link to ticket: https://www.notion.so/2022-Echo-Internship-07a11d3d30da40098b4ec56c93419db0?p=547fc7dcd8714c8ca609a0a2f348c357&pm=s
Notes for the reviewer: Added a flash alert feature that will display when clicking the create announcement.
Contributors: elijah jason will gene francisco

Notification bug

---

Gemfile.lock
app/views/shared/_navbar.html.erb

ID number: 89
Branch name: letter-opener-access
Description: Logged in students should not have access to the Letter Opener...
Link to ticket: https://www.notion.so/3c617b3aba60438ea07f6065f97dafb4?v=ed93b67784f4486eaad077353b10faca&p=68eac9e0edde4f43bd048862c2c7fd10&pm=s
Contributors: Anthony, Charlie, Immanuel

:bug: logged in students do not have access to the Letter Opener

---

app/controllers/api/base_controller.rb
app/controllers/api/v1/auths_controller.rb
app/models/user.rb

ID number: 104
Branch name: rails-student-login
Description: Added login functionality from react side to rails side by adding authenticate user function receiving from react side verifying user and password through the auths controller create method
Link to ticket: https://www.notion.so/2022-Golf-Internship-a4556022acd84408a34062ba09f9e6f8?p=aadbed9474a84919964f13b8cb2e1d71&pm=s
Contributors: Sarah, Charlie, Immanuel, Ramirez

✨ :Rails student login

---

app/views/shared/_navbar.html.erb

ID number: 105
Branch name: nav-menu-mobile-fix
Description: Added styling for dropdown menu to appear above page content
Contributors: Charlie, Ramirez, Immanuel

🐛 :Added styling for dropdown menu to appear above page content

---

config/puma.rb

ID number:
106
Branch name:
move-to-3000
Description:
Moved listening port to 3000 from 3001
https://www.notion.so/2022-Hotel-Internship-870dd2f2a8c741a3a006a92f7a9598c9?p=cbc7ab5a71064683a448dc120d742452&pm=s
Contributors:
Matt, Torin, Moss, Monica, Chris, Aileen in spirit

changed port to 3000 from 3001

---

config/environments/development.rb

ID number: 117
Branch name: letter-opener-bug
Description: updating letter opener config file to port 3000 to fix bug
Link to ticket: https://www.notion.so/2022-Hotel-Internship-870dd2f2a8c741a3a006a92f7a9598c9?p=1392d5f93bab45b39359424a351ab570&pm=s
Notes for the reviewer: N/A
Contributors: Moss, Sarah

squashed letter opener bug and changed port to 3000

---

app/views/static/conduct.html.erb

ID number:
113
Branch name:
conduct-links
Description:
changed the display to match the display on the react app.
https://www.notion.so/2022-Hotel-Internship-870dd2f2a8c741a3a006a92f7a9598c9?p=d875e2e7f73840619b8ff853a0eca2e7&pm=s
Contributors:
Everyone

changed display to match react app code of conduct display. fixed links

---

app/assets/stylesheets/administrate/components/_attributes.scss
app/assets/stylesheets/administrate/components/_pagination.scss
app/assets/stylesheets/administrate/library/_variables.scss
app/assets/stylesheets/components/pagination.css

ID number: 115
Branch name: link-color
Description: Made all hyperlinks and pagination links learn purple
Link to ticket: https://www.notion.so/Rails-Change-link-color-1cf28a3ea1454ffc8e0d12c118b32b81?pvs=4
Contributors: Matt, Monica, Chris, Torin, Moss, Aileen

made pagination links learn purple

---

app/controllers/api/v1/auths_controller.rb

ID number: 120
Branch name: student-absences
Description: Added absences to jwt
Link to ticket: https://www.notion.so/React-Student-Absences-bab50bcbfb304b94a5b677c0afe1b702?pvs=4
Contributors: Monica, Chris, Matt

added absences to jwt

---

app/controllers/api/v1/auths_controller.rb

ID number: 123
Branch name: student-assessments
Description: made necessary changes to pass database assessment info rather than mock data
Link to ticket: https://www.notion.so/2022-Hotel-Internship-870dd2f2a8c741a3a006a92f7a9598c9?p=ff5c26ded3f14f1eb010740cde659b71&pm=s
Notes for the reviewer: N/A
Contributors: Matt, Monica, Aileen, Chris, Moss

made necessary changes to dynamically pass assessment data to front end

---

app/views/static/contributors.html.erb

ID number: 126
Branch name: contributor-cards-center
Description: 💄 [126] center the margins for contributors' cards
Link to ticket: https://www.notion.so/2023-Alpha-Internship-d8fb274ab0b24178a8493692e28821fa?p=261765cff84d45428b9ffc102f11e17c&pm=s
Contributors: Xavier, Manny, Ronnie, Leo

💄 [126] center the margins for contributors cards

---

app/assets/stylesheets/administrate/components/_attributes.scss

ID number:
Branch name:
Description:
Contributors:

💄 [128] aligned-items for attribute-label

---

app/views/static/AboutUs.html.erb

ID number:
Branch name:
Description:
Contributors:

🚚 [131] removed About.html.erb

---

app/dashboards/assessment_dashboard.rb
app/models/assessment.rb

ID number:  134
Branch name: assessment-status
Description: adds Rails:Enum for assessment status
Link to ticket: https://www.notion.so/2023-Alpha-Internship-d8fb274ab0b24178a8493692e28821fa?p=f11a7cdd4de5469383d8e97014210d50&pm=s
Contributors: Xavier, Manny, Ronnie, Leo

✨ [134] adds  Rails:Enum for Assessment status

---

app/views/shared/_navbar.html.erb

ID number:[140]
Branch name: hamburger-menu
Description: 💄
Link to ticket: https://www.notion.so/2023-Alpha-Internship-d8fb274ab0b24178a8493692e28821fa?p=26c7ef5c427c4f5ea7d4233d5e59da68&pm=s
Contributors: Xavier, Manny, Leo, Ronnie

Changed the hamburger menu font to LEARN purple

---

app/dashboards/student_dashboard.rb
app/models/student.rb

ID number: 138
Branch name: absence-values
Description: Made a range for students absence field (0..10) which validated numerically
Link to ticket: https://www.notion.so/2023-Alpha-Internship-d8fb274ab0b24178a8493692e28821fa?p=ad408afbb420432aa4c191cf917ecdb7&pm=s
Contributors: Manny, Ronnie, Leo, Xavier

 💄[138] fixed student absences 0..10

---

app/views/static/contributors.html.erb

ID number: 155
Branch name: sorted-contributors
Description: 
Link to ticket: https://www.notion.so/2023-Bravo-Internship-55e260cc1a2f42538409fa514093c73b?p=a8cf4ea4d1844871b4909227aabb809a&pm=s
Contributors: Evelyn, Jose, Valeria

added code functionality for contributors

---

app/views/static/contributors.html.erb

ID number: 168
Branch name:
Description: Added about me to the contributers
Link to ticket: https://www.notion.so/3c617b3aba60438ea07f6065f97dafb4?v=ed93b67784f4486eaad077353b10faca&p=151024e0a56b46aa9d1690cdeb1039f0&pm=s
Contributors: Valeria,Eddie,Evelyn,Jose

Added about me to contributers pt2.
